### ISSUE TITLE
Gradient calculation

### ISSUE THREAD

**Issue by Valdiolus** [creotiv/mlclubua#1]
Возникли сложности с вычислением градиента. Возможно, не до конца понял из видео что делать.
Получается, градиент dW (analytic_grad), допустим в SVM, вычисляется для каждого из элемента массива весов W(3073х10)? Мы поочередно добавляем некий step к i-ому элементу W, далее пересчитываем loss и сравниваем new_loss с old_loss, делим на шаг step и это и есть градиент? Потому что у меня получается числа на порядок больше чем при вычислении grad_numerical.

**Comment by Valdiolus** [comment]
Проблема решена

**Comment by creotiv** [comment]
Молодец!)
